on: [push, pull_request]
name: tests
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.sha || '' }}
  cancel-in-progress: true
jobs:
  # Run unit tests
  tests:
    name: "py-${{ matrix.python-version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pydeps ${{ matrix.os }}
        run: |
          make install-pydeps

      - name: Tests
        run: |
          make test

  # Run linters
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: "Run linters"
        run: |
          sudo apt install markdownlint
          python3 -m pip install --upgrade black ruff rstcheck
          python3 -m pip freeze
          make lint-all
